name: Try fail fast

on:
  push:
    branches:
      - master

jobs:
  # prepare-dessert:
  #   runs-on: ubuntu-latest
  #   # 為了避免無限迴圈，所以job不能依賴自己
  #   # needs: prepare-dessert
  #   # if: ${{ needs.prepare-dessert.outputs.result == 'success' }} 
  #   strategy:
  #     matrix:
  #       fruit: [mango, strawberry]
  #       dessert: ['ice cream', cake]
  #       include:
  #         - size: small
  #         - size: large
  #           dessert: 'ice cream'
  #         - fruit: mango
  #           decoration: chocolate
  #   steps:
  #     - name: throw error
  #       if: ${{ matrix.fruit == 'mango'}}
  #       run: |
  #         echo "Using exit 1 to test if this can stop next job" 
  #         exit 1
  #     - name: The first step of a matrix job
  #       if: ${{ success() }}
  #       run: |
  #         echo "${{ matrix.fruit }} ${{ matrix.dessert }} ${{ matrix.decoration }} ${{ matrix.size }}"

  # prepare-dessert:
  #   runs-on: ubuntu-latest
  #   # continue-on-error: false
  #   strategy:
  #     # fail-fast: true
  #     matrix:
  #       fruit: [mango, strawberry]
  #       dessert: ['ice cream', cake]
  #       include:
  #         - size: small
  #         - size: large
  #           dessert: 'ice cream'
  #         - fruit: mango
  #           decoration: chocolate
  #         - fruit: raspberry
  #         - fruit: raspberry
  #           dessert: 'ice cream'
  #   steps:
  #     - name: throw error
  #       if: ${{ matrix.fruit != 'mango'}}
  #       run: |
  #         echo "Throw error on purpose" 
  #         exit 1
  #     - name: print something
  #       run: echo ${{ matrix.fruit}} ${{ matrix.dessert}} 

  next-job:
    runs-on: ubuntu-latest
    continue-on-error: true
    # needs: prepare-dessert
    # strategy:
    #   fail-fast: true
    steps:
      - name: throw error
        run: |
          echo "Throw error on purpose" 
          exit 1
      - name: after throw error
        run: |
          echo "This is after throw error"